---
title: "Movies_EDA_Project"
output: html_document
---
# trying to set up git
Load packages:
```{r}
library(readr)
library(tidyverse)
library(lubridate)
library(jsonlite)
library(gt)
library(data.table)
```


Read data:
```{r}
movies <- read_csv("the-movies-dataset/movies_metadata.csv")
credits <- read_csv("the-movies-dataset/credits.csv")
keywords <- read_csv("the-movies-dataset/keywords.csv")
links <- read_csv("the-movies-dataset/links.csv")
ratings <- read_csv("the-movies-dataset/ratings.csv")
```


Check NAs:
```{r}
str(movies)

sum.NA.total <- movies %>%
  select(everything()) %>%
  summarise_all(funs(sum(is.na(.))))

PropOfNA.total <- (sum.NA.total/nrow(movies))*100
SumNA.prop <- PropOfNA.total %>% map_dbl(sum)
kable(SumNA.prop, format = "markdown")

```


# EDA
```{r}
# freq table for # movies per year:
movies_byYear <- movies %>% 
  group_by(year(release_date)) %>% 
  count()

# barplot of # movies per year:
ggplot(movies_byYear, aes(`year(release_date)`, n)) + geom_bar(stat="identity", width = 0.5)

# set movies with budget 0 to NA
movies$budget[movies$budget == 0] <- NA 
summary(movies$budget)

```



# to unpack genres column:
```{r}
metadata <- fread("the-movies-dataset/movies_metadata.csv", select=c('adult', 'genres', 'release_date', 'original_language', 'original_title', 'id', 'imdb_id'), fill=T)
metadata <- metadata[!is.na(as.integer(id))]


metadata <- metadata[, genre := gsub("\'","\"", metadata$genre)]

metadata[, c('original_language', 'adult', "imdb_id") := NULL]

genres <- metadata[, unlist(lapply(genre, fromJSON), recursive=F)['name'], by=id]
sorted.genres <- genres[, .N, by=name][order(-N)]
sorted.genres[1:20]

genres[, dummy := 1]

encoded.genres <- dcast(na.omit(genres[,.SD[1:3], by=id])[name %in% sorted.genres[1:20, name]], 
                        id ~  name, value.var='dummy', fill=0)
data.w.genre <- merge(encoded.genres,
      metadata[, .(id, original_title, release_date)], 
      all.x=T, by="id")

```














